### ISSUE TITLE
How can i add chunk to a measurement?

### ISSUE THREAD

**Issue by KhushalGoyal** [nuralogix/dfx-api-client-python#5]
Hello Team,

I want to implement a demo in my app using your APIs **(https://dfxapiversion10.docs.apiary.io/#introduction),** I am having some issue while adding the chunks to a specific measurement like a chunk can be in form of binary array as I am using it on the client-side itself so, there is not much information regarding do so. 
Apart from that while using end to end example given on the git **(https://github.com/nuralogix/dfx-e2e-demo-python)** 
I am facing one more issue as well that is **"ANALYSIS_ERROR: No image found for liveness score".** Please can you provide some documentation and someone to help me out on this?

Note: I am currently using a demo account

Thanks.

**Comment by sambhare** [comment]
Hello

Adding chunks can be achieved using either 
1. Websockets. You have to encode the chunk into a protobuf as shown here: https://github.com/nuralogix/dfx-api-client-python/blob/master/dfxapiclient/measurements.py#L146

or 
2. REST shown here: https://github.com/nuralogix/dfx-api-client-python/blob/master/dfxapiclient/measurements.py#L111

Chunks are produced only using the DFX SDK.

Regarding your second issue it is being caused by a change in our cloud that is not being handled in the study config file you have. For now, we will have to change the study you are using on the backend. I will have my team contact you about it shortly. 

We will be publishing a new end to end demo shortly that demonstrates how to dynamically update your study config file at runtime.

**Comment by KhushalGoyal** [comment]
@sambhare 
That would be very helpful.

**Comment by sambhare** [comment]
Hello Khushal, could please you try again and see if the ANALYSIS_ERROR issue is resolved for you?

**Comment by KhushalGoyal** [comment]
Thank You @sambhare it is working now and by any chance does your team working on building the SDK in javascript.

**Comment by KhushalGoyal** [comment]
@sambhare , I am also facing one more issue
```bash
AttributeError: 'Collector' object has no attribute 'forceComplete'
```

**Comment by sambhare** [comment]
Could you please upgrade to version 4.4.1.1 of libdfxpython? Available here: https://deepaffex.ai/developers-sdk

**Comment by KhushalGoyal** [comment]
Okay, Thanks @sambhare for the help.
